// export const host = "http://localhost:5000";
// export const host = "https://gainimpact-chatapp.herokuapp.com"
export const loginRoute = `/api/auth/login`;
export const registerRoute = `/api/auth/register`;
export const logoutRoute = `/api/auth/logout`;
export const allUsersRoute = `/api/auth/allusers`;
export const sendMessageRoute = `/api/messages/addmsg`;
export const recieveMessageRoute = `/api/messages/getmsg`;
export const setProfilePictures = `/api/auth/setprofilepicture`;
export const getAllMsg = `/api/messages/getAllMsg`;
